- name: installing utilities on ubuntu
  hosts: all 
  tasks:
    - name: installing utilitis on ubuntu
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      become: yes
      loop: "{{packages}}"
    - name: debug variables
      ansible.builtin.debug:
        var: purpose      